package shellinit

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const (
	posixExe = "/opt/cc shelf/ccshelf"
	winExe   = `C:\Program Files\ccshelf\ccshelf.exe`
)

func golden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if os.Getenv("UPDATE_GOLDEN") != "" {
		if err := os.WriteFile(path, []byte(got), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if norm(got) != norm(string(want)) {
		t.Errorf("%s mismatch\n--- got ---\n%s\n--- want ---\n%s", name, got, want)
	}
}

func TestGenerateGolden(t *testing.T) {
	profiles := []string{"sre", "frontend", "seo-2", "sre"}
	tests := []struct {
		shell, goos, exe, file string
	}{
		{Bash, "linux", posixExe, "bash.golden"},
		{Zsh, "darwin", posixExe, "zsh.golden"},
		{Fish, "linux", "/opt/it's/ccshelf", "fish.golden"},
		{Pwsh, "windows", winExe, "pwsh.golden"},
		{Pwsh, "linux", "/opt/it's/ccshelf", "pwsh_posix.golden"},
		{Cmd, "windows", winExe, "cmd.golden"},
	}
	for _, tt := range tests {
		t.Run(tt.file, func(t *testing.T) {
			got, err := Generate(tt.shell, tt.goos, profiles, tt.exe)
			if err != nil {
				t.Fatal(err)
			}
			golden(t, tt.file, got)
		})
	}
}

func TestGenerateEmptyProfiles(t *testing.T) {
	got, err := Generate(Bash, "linux", nil, "/bin/ccshelf")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(got, "run") && strings.Contains(got, "()") {
		t.Errorf("unexpected function in %q", got)
	}
	if !strings.HasPrefix(got, "# ccshelf shell integration") {
		t.Errorf("missing header: %q", got)
	}
}

func TestGenerateRejects(t *testing.T) {
	hostileNames := []string{
		"", "UPPER", "a b", "a;b", "a'b", `a"b`, "a$b", "a`b", "$(id)", "../x", "a/b", `a\b`, "-lead", "a\nb", "a\x00b",
		"x" + strings.Repeat("a", 63), "é", "a.b", "a_b",
	}
	for _, n := range hostileNames {
		for _, sh := range Shells() {
			goos := "linux"
			if sh == Cmd {
				goos = "windows"
			}
			if out, err := Generate(sh, goos, []string{"ok", n}, "/bin/ccshelf"); err == nil || out != "" {
				if sh == Cmd {
					if _, err = Generate(sh, goos, []string{n}, winExe); err == nil {
						t.Errorf("%s accepted profile %q", sh, n)
					}
					continue
				}
				t.Errorf("%s accepted profile %q", sh, n)
			}
		}
	}
	badExe := []struct{ shell, goos, exe string }{
		{Bash, "linux", ""},
		{Bash, "linux", "ccshelf"},
		{Bash, "linux", "./ccshelf"},
		{Bash, "linux", "/bin/cc\nshelf"},
		{Bash, "linux", "/bin/cc\x1bshelf"},
		{Bash, "linux", "/bin/\xff"},
		{Bash, "linux", "/bin/\u202Eshelf"},
		{Pwsh, "windows", "ccshelf.exe"},
		{Pwsh, "windows", `C:rel\x`},
		{Pwsh, "windows", `\\`},
		{Cmd, "windows", `C:\a"b\x.exe`},
		{Cmd, "windows", `C:\100%\x.exe`},
		{Cmd, "windows", `C:\a$b\x.exe`},
		{Cmd, "linux", "/bin/ccshelf"},
		{"tcsh", "linux", "/bin/ccshelf"},
	}
	for _, tt := range badExe {
		if _, err := Generate(tt.shell, tt.goos, []string{"a"}, tt.exe); err == nil {
			t.Errorf("Generate(%s, %s, %q) accepted", tt.shell, tt.goos, tt.exe)
		}
	}
	for _, exe := range []string{`D:/tools/ccshelf.exe`, `\\server\share\ccshelf.exe`} {
		if _, err := Generate(Pwsh, "windows", []string{"a"}, exe); err != nil {
			t.Errorf("windows path %q rejected: %v", exe, err)
		}
	}
}

func TestNames(t *testing.T) {
	if FunctionName("sre") != "cs-sre" {
		t.Error("FunctionName")
	}
	if !ValidProfileName("a-1") || ValidProfileName("A") {
		t.Error("ValidProfileName")
	}
}

func TestWriteCmdShims(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "shims")
	paths, err := WriteCmdShims(dir, []string{"sre", "dev"}, winExe)
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 2 || filepath.Base(paths[0]) != "cs-dev.cmd" {
		t.Fatalf("paths = %v", paths)
	}
	b, err := os.ReadFile(paths[1])
	if err != nil {
		t.Fatal(err)
	}
	want := "@echo off\r\nrem generated by ccshelf shell-init. Do not edit.\r\n\"" + winExe + "\" run sre %*\r\n"
	if string(b) != want {
		t.Errorf("shim = %q", b)
	}
	// Re-running replaces.
	if _, err = WriteCmdShims(dir, []string{"sre"}, winExe); err != nil {
		t.Errorf("rewrite: %v", err)
	}
	if runtime.GOOS != "windows" {
		fi, _ := os.Stat(dir)
		if fi.Mode().Perm() != 0o700 {
			t.Errorf("dir mode %v", fi.Mode().Perm())
		}
	}
	// Errors.
	if _, err = WriteCmdShims(dir, []string{"bad name"}, winExe); err == nil {
		t.Error("bad profile accepted")
	}
	if _, err = WriteCmdShims(dir, []string{"a"}, "rel.exe"); err == nil {
		t.Error("relative exe accepted")
	}
	if _, err = WriteCmdShims("", []string{"a"}, winExe); err == nil {
		t.Error("empty dir accepted")
	}
	file := filepath.Join(t.TempDir(), "afile")
	if err = os.WriteFile(file, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err = WriteCmdShims(filepath.Join(file, "sub"), []string{"a"}, winExe); err == nil {
		t.Error("directory under a file accepted")
	}
}

func TestWriteCmdShimsRefusesSymlink(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "elsewhere")
	if err := os.WriteFile(target, []byte("keep"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, filepath.Join(dir, "cs-a.cmd")); err != nil {
		t.Skipf("symlinks not available: %v", err)
	}
	if _, err := WriteCmdShims(dir, []string{"a"}, winExe); err == nil {
		t.Error("symlink was replaced")
	}
	if b, _ := os.ReadFile(target); string(b) != "keep" {
		t.Errorf("target modified: %q", b)
	}
}

// fakeExe writes a script that records its arguments, one per line, to the
// file named by FAKE_OUT, in a directory whose name has a space and a quote.
func fakeExe(t *testing.T) (exe, out string) {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "dir with 'quote' and space")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	exe = filepath.Join(dir, "ccshelf")
	script := "#!/bin/sh\nprintf '%s\\n' \"$@\" > \"$FAKE_OUT\"\n"
	if err := os.WriteFile(exe, []byte(script), 0o700); err != nil { //nolint:gosec // test script must be executable
		t.Fatal(err)
	}
	return exe, filepath.Join(t.TempDir(), "args.txt")
}

func TestSourceInRealShells(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("POSIX shells are not available on Windows")
	}
	for _, sh := range []string{Bash, Zsh, Fish} {
		t.Run(sh, func(t *testing.T) {
			bin, err := exec.LookPath(sh)
			if err != nil {
				t.Skipf("%s is not installed", sh)
			}
			exe, out := fakeExe(t)
			script, err := Generate(sh, runtime.GOOS, []string{"sre", "my-profile"}, exe)
			if err != nil {
				t.Fatal(err)
			}
			init := filepath.Join(t.TempDir(), "init")
			if err = os.WriteFile(init, []byte(script), 0o600); err != nil {
				t.Fatal(err)
			}
			var cmdline string
			switch sh {
			case Fish:
				cmdline = `source "$INIT"; cs-my-profile --resume 'two words' "$HOSTILE"`
			default:
				cmdline = `eval "$(cat "$INIT")"; cs-my-profile --resume 'two words' "$HOSTILE"`
			}
			cmd := exec.Command(bin, "-c", cmdline) //nolint:gosec // fixed shell names
			cmd.Env = append(os.Environ(), "INIT="+init, "FAKE_OUT="+out, "HOSTILE=$(touch pwned); `id` ' \"")
			cmd.Dir = t.TempDir()
			if b, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("%s failed: %v\n%s", sh, err, b)
			}
			got, err := os.ReadFile(out)
			if err != nil {
				t.Fatal(err)
			}
			want := "run\nmy-profile\n--resume\ntwo words\n$(touch pwned); `id` ' \"\n"
			if string(got) != want {
				t.Errorf("args = %q, want %q", got, want)
			}
			if _, err := os.Stat(filepath.Join(cmd.Dir, "pwned")); err == nil {
				t.Error("hostile argument was executed")
			}
		})
	}
}

func TestSourceInPwsh(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("uses a POSIX fake executable")
	}
	bin, err := exec.LookPath("pwsh")
	if err != nil {
		t.Skip("pwsh is not installed")
	}
	exe, out := fakeExe(t)
	script, err := Generate(Pwsh, runtime.GOOS, []string{"sre"}, exe)
	if err != nil {
		t.Fatal(err)
	}
	init := filepath.Join(t.TempDir(), "init.ps1")
	if err = os.WriteFile(init, []byte(script), 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(bin, "-NoProfile", "-Command", `. $env:INIT; cs-sre --resume 'two words'`) //nolint:gosec // fixed binary
	cmd.Env = append(os.Environ(), "INIT="+init, "FAKE_OUT="+out)
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("pwsh failed: %v\n%s", err, b)
	}
	got, _ := os.ReadFile(out)
	if string(got) != "run\nsre\n--resume\ntwo words\n" {
		t.Errorf("args = %q", got)
	}
}

// norm makes comparisons independent of git line-ending conversion.
func norm(s string) string { return strings.ReplaceAll(s, "\r\n", "\n") }
