package shellinit

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/yorch/ccshelf/internal/ui"
)

// Prefix is put before the profile name to form the function name.
const Prefix = "cs-"

// Supported shell names.
const (
	// Bash is bash.
	Bash = "bash"
	// Zsh is zsh.
	Zsh = "zsh"
	// Fish is fish.
	Fish = "fish"
	// Pwsh is PowerShell (Windows PowerShell and PowerShell 7).
	Pwsh = "pwsh"
	// Cmd is cmd.exe with doskey macros (see WriteCmdShims for shims).
	Cmd = "cmd"
)

// Shells returns the supported shell names.
func Shells() []string { return []string{Bash, Zsh, Fish, Pwsh, Cmd} }

var profileRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,62}$`)

// ValidProfileName reports whether name may be used in a generated function.
func ValidProfileName(name string) bool { return profileRe.MatchString(name) }

// FunctionName returns the shell function name for a profile: "cs-" plus name.
func FunctionName(profile string) string { return Prefix + profile }

// Generate returns the script for shell. profiles are validated, sorted and
// de-duplicated. exe is the absolute path of the ccshelf executable. goos is
// the operating system the script is for (it decides what an absolute path
// looks like, and "cmd" requires "windows"). An empty profile list yields a
// script with only the header.
func Generate(shell, goos string, profiles []string, exe string) (string, error) {
	names, err := checkInputs(shell, goos, profiles, exe)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(header(shell))
	switch shell {
	case Bash, Zsh:
		q, err := ui.QuotePOSIX(exe)
		if err != nil {
			return "", fmt.Errorf("quoting the ccshelf executable path: %w", err)
		}
		for _, n := range names {
			// An existing alias with the same name would be expanded in the
			// function name position and abort the eval with a parse error (and
			// would shadow the function afterwards), so remove it first and use
			// the "function" form, whose name is never alias-expanded.
			fmt.Fprintf(&b, "unalias %s 2>/dev/null || true\n", FunctionName(n))
			fmt.Fprintf(&b, "function %s { %s run %s \"$@\"; }\n", FunctionName(n), q, n)
		}
	case Fish:
		q := fishQuote(exe)
		for _, n := range names {
			fmt.Fprintf(&b, "function %s --description 'ccshelf profile %s'\n    %s run %s $argv\nend\n", FunctionName(n), n, q, n)
		}
	case Pwsh:
		q := psQuote(exe)
		for _, n := range names {
			fmt.Fprintf(&b, "function %s { & %s run %s @args }\n", FunctionName(n), q, n)
		}
	case Cmd:
		for _, n := range names {
			b.WriteString("doskey " + FunctionName(n) + "=\"" + exe + "\" run " + n + " $*\r\n")
		}
	}
	return b.String(), nil
}

func header(shell string) string {
	lines := []string{
		"ccshelf shell integration (generated by: ccshelf shell-init " + shell + ").",
		"Defines one function per profile: cs-<profile> runs `ccshelf run <profile>`",
		"and passes the remaining arguments through to claude.",
	}
	switch shell {
	case Bash, Zsh:
		lines = append(lines, `Load it with: eval "$(ccshelf shell-init `+shell+`)"`)
	case Fish:
		lines = append(lines, "Load it with: ccshelf shell-init fish | source")
	case Pwsh:
		lines = append(lines, "Load it with: ccshelf shell-init pwsh | Out-String | Invoke-Expression")
	case Cmd:
		lines = append(lines,
			"Load it with: ccshelf shell-init cmd > \"%TEMP%\\ccshelf-init.cmd\" && call \"%TEMP%\\ccshelf-init.cmd\"",
			"These doskey macros last for this console window only. For persistent",
			"commands, use .cmd shims on PATH instead.")
	}
	prefix := "# "
	eol := "\n"
	if shell == Cmd {
		prefix, eol = "REM ", "\r\n"
	}
	var b strings.Builder
	for _, l := range lines {
		b.WriteString(prefix + l + eol)
	}
	return b.String()
}

// checkInputs validates everything that ends up in a script and returns the
// sorted, de-duplicated profile names.
func checkInputs(shell, goos string, profiles []string, exe string) ([]string, error) {
	switch shell {
	case Bash, Zsh, Fish, Pwsh, Cmd:
	default:
		return nil, fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(Shells(), ", "))
	}
	if shell == Cmd && goos != "windows" {
		return nil, errors.New("the cmd shell is only available on windows")
	}
	if err := checkExe(shell, goos, exe); err != nil {
		return nil, err
	}
	return checkProfiles(profiles)
}

func checkProfiles(profiles []string) ([]string, error) {
	seen := map[string]bool{}
	var names []string
	for _, p := range profiles {
		if !ValidProfileName(p) {
			return nil, fmt.Errorf("invalid profile name %q: must match %s", ui.Sanitize(p), profileRe)
		}
		if !seen[p] {
			seen[p] = true
			names = append(names, p)
		}
	}
	sort.Strings(names)
	return names, nil
}

func checkExe(shell, goos, exe string) error {
	if exe == "" {
		return errors.New("the ccshelf executable path is empty")
	}
	if !utf8.ValidString(exe) {
		return errors.New("the ccshelf executable path is not valid UTF-8")
	}
	if ui.HasControl(exe) {
		return errors.New("the ccshelf executable path contains a control or invisible character")
	}
	if !isAbs(goos, exe) {
		return fmt.Errorf("the ccshelf executable path %q is not absolute", exe)
	}
	if shell == Cmd && strings.ContainsAny(exe, `"%$`) {
		return fmt.Errorf("the ccshelf executable path %q contains a character that cmd.exe cannot carry safely (\", %% or $)", exe)
	}
	return nil
}

// isAbs reports whether p is absolute for goos, independent of the host.
func isAbs(goos, p string) bool {
	if goos == "windows" {
		if strings.HasPrefix(p, `\\`) {
			// UNC: \\server\share needs both parts.
			parts := strings.Split(p[2:], `\`)
			return len(parts) >= 2 && parts[0] != "" && parts[1] != ""
		}
		return len(p) >= 3 && ((p[0] >= 'a' && p[0] <= 'z') || (p[0] >= 'A' && p[0] <= 'Z')) &&
			p[1] == ':' && (p[2] == '\\' || p[2] == '/')
	}
	return strings.HasPrefix(p, "/")
}

// fishQuote always single-quotes s for fish, escaping backslash and quote.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	return "'" + s + "'"
}

// psQuote always single-quotes s for PowerShell, doubling every character
// PowerShell treats as a single quote.
func psQuote(s string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\'', '‘', '’', '‚', '‛':
			b.WriteRune(r)
		}
		b.WriteRune(r)
	}
	b.WriteByte('\'')
	return b.String()
}

// WriteCmdShims writes one "cs-<profile>.cmd" batch file per profile into dir,
// which is created with mode 0700 if missing, and returns the paths written.
// Each shim runs "<exe> run <profile>" with the remaining arguments. Existing
// shims are replaced atomically. A symlink at a target path is refused. exe is
// validated with the rules for cmd.exe on Windows.
func WriteCmdShims(dir string, profiles []string, exe string) ([]string, error) {
	names, err := checkInputs(Cmd, "windows", profiles, exe)
	if err != nil {
		return nil, err
	}
	if dir == "" {
		return nil, errors.New("shim directory is empty")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("creating shim directory %s: %w", dir, err)
	}
	var written []string
	for _, n := range names {
		path := filepath.Join(dir, FunctionName(n)+".cmd")
		content := "@echo off\r\nrem generated by ccshelf shell-init. Do not edit.\r\n\"" + exe + "\" run " + n + " %*\r\n"
		if err := writeFileAtomic(path, []byte(content)); err != nil {
			return written, err
		}
		written = append(written, path)
	}
	return written, nil
}

func writeFileAtomic(path string, data []byte) error {
	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to replace symlink %s", path)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".shim-*.tmp")
	if err != nil {
		return fmt.Errorf("creating temporary file for %s: %w", path, err)
	}
	name := tmp.Name()
	fail := func(err error) error {
		_ = tmp.Close()
		_ = os.Remove(name)
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		return fail(fmt.Errorf("writing %s: %w", name, err))
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(name)
		return fmt.Errorf("closing %s: %w", name, err)
	}
	if err := os.Rename(name, path); err != nil {
		_ = os.Remove(name)
		return fmt.Errorf("replacing %s: %w", path, err)
	}
	return nil
}
