package scaffold

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// update rewrites the golden trees and the generated files of the example
// repo: go test ./internal/scaffold -run 'Golden|Example' -update
var update = flag.Bool("update", false, "rewrite the golden trees and the generated files of examples/org-data-repo")

// compareTree compares the files below root with the golden directory, or
// rewrites the golden directory with -update.
func compareTree(t *testing.T, root, golden string) {
	t.Helper()
	got := readTree(t, root)
	if *update {
		if err := os.RemoveAll(golden); err != nil {
			t.Fatal(err)
		}
		writeTree(t, golden, got)
		return
	}
	want := readTree(t, golden)
	var names []string
	for n := range got {
		names = append(names, n)
	}
	for n := range want {
		if _, ok := got[n]; !ok {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	for _, n := range names {
		g, gok := got[n]
		w, wok := want[n]
		switch {
		case !wok:
			t.Errorf("%s: generated but not in the golden tree (run with -update)", n)
		case !gok:
			t.Errorf("%s: in the golden tree but not generated (run with -update)", n)
		case g != w:
			t.Errorf("%s differs from the golden tree (run with -update):\n--- got\n%s\n--- want\n%s", n, g, w)
		}
	}
}

func TestGoldenNewRepo(t *testing.T) {
	dir := t.TempDir()
	p := baseParams()
	p.ExampleProfile = true
	p.RunnerLabel = "linux-runners"
	run(t, dir, p, ApplyOptions{})
	compareTree(t, dir, filepath.Join("testdata", "golden", "new"))
}

func TestGoldenProfilesOnly(t *testing.T) {
	dir := t.TempDir()
	p := Params{Org: "Acme", PlatformOwners: []string{"@acme/platform"}, CcshelfRef: strings.Repeat("a", 40), CcshelfVersion: "v0.1.0", ProfilesOnly: true, ExampleProfile: true}
	run(t, dir, p, ApplyOptions{})
	compareTree(t, dir, filepath.Join("testdata", "golden", "profiles-only"))
}

func TestGoldenAdoptRepo(t *testing.T) {
	dir := t.TempDir()
	repo := legacyRepo()
	repo[".github/CODEOWNERS"] = "/plugins/tools-a/ @legacy/a-team\n/plugins/tools-b/ @legacy/b-team\n/.github/ @legacy/platform\n"
	writeTree(t, dir, repo)
	p := Params{PlatformOwners: []string{"@legacy/platform"}, Owner: "@legacy/default", CcshelfRef: strings.Repeat("c", 40), CcshelfVersion: "v0.2.0"}
	run(t, dir, p, ApplyOptions{WriteSuggestions: true})
	compareTree(t, dir, filepath.Join("testdata", "golden", "adopt"))
}

// The files that every org data repo shares are generated by this package;
// the starter template under examples/ keeps its own copies of them so that it
// stays a complete, copyable repository. This test fails, and -update fixes
// it, when the copies drift from the templates. The rest of the starter
// (plugins, profiles, CODEOWNERS, ccshelf.toml, README) is hand-written.
func TestExampleSharedFilesAreGenerated(t *testing.T) {
	example := filepath.Join("..", "..", "examples", "org-data-repo")
	if _, err := os.Stat(example); err != nil {
		t.Skip("the starter template is not part of this checkout")
	}
	dir := t.TempDir()
	p := Params{
		MarketplaceName: "acme", PlatformOwners: []string{"@acme/platform"}, CcshelfVersion: "v0.1.0",
		Skip: map[Group]bool{GroupConfig: true, GroupMarketplace: true, GroupSidecars: true, GroupCodeowners: true, GroupReadme: true},
	}
	run(t, dir, p, ApplyOptions{})
	for n, want := range readTree(t, dir) {
		path := filepath.Join(example, filepath.FromSlash(n))
		if *update {
			writeTree(t, example, map[string]string{n: want})
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("%s: %v (run: go test ./internal/scaffold -run Example -update)", n, err)
			continue
		}
		if string(got) != want {
			t.Errorf("%s drifted from the template of internal/scaffold (run: go test ./internal/scaffold -run Example -update)", n)
		}
	}
}
